# VERSION 4

[buildPlans.iosevka-ak2]
family = "Iosevka AK2"
design = [
    "cv01", # a (default)
    "VXBM", # b rounded bottom
    "VXBP", # d rounded bottom
    "cv84", # f serifed
    "cv11", # g default
    "VXCB", # h default
    "cv06", # i asymmtetric serif
    "cv58", # j rounded
    "cv68", # k default
    "cv10", # l z shaped
    # "VXDA", # l asymmetric serif
    "cv26", # m with shorter middle leg
    "VXCF", # n default
    "VXCR", # p rounded top,
    "VXCS", # q rounded top
    "cv86", # r serif
    "VXDC", # t sharp bottom
    "cv90", # u rounded bottom
    "VXBF", # y with a tail
    "VXBD", # z default
    "cv73", # A default,
    "VXAQ", # B rounded
    "VXBG", # D default
    "cv92", # G rounded bottom
    "v-capital-j-serifed-both-sides", # J serif asymmetric?
    "VXCI", # M default
    "VXCA", # Q rounded bottom
    "cv82", # R default
    "cv80", # Y straight
    "cv13", # 0 slash
    "cv51", # 1 serif
    "cv46", # 3 sharp
    "VXAV", # 4 like calculator
    "VXAE", # 6 rounded bottom
    "VXAX", # 7 with cross over
    "cv96", # 9 rounded
    "cv17", # ~ middle
    "cv61", # * middle with 6 legs
    "cv30", # ^ middle
    "VXAO", # ( ROUNDED
    "cv37", # { middle
    "VXBJ", # # slanted with space
    "VXAI", # & rounded
    "cv32", # @ nice
    "cv54", # $ dollar small,
    "cv63", # % default?
    "cv67", # <= ligature"
]
# overload…
italic = [
    "VXBU", # a curly
    "cv53", # f curly
    "cv24", # g curly
    "VXCC", # h curly serif
    "cv04", # i curly asymmetric
    "VXDE", # j curly asymmetric
    "cv08", # l curly asymmetric serif
    "VXCT", # q curly rounded top
    "cv40", # t curly bottom
    "VXBT", # u curly
    "cv72", # v curly bottom
    "cv78", # x curly bottom
    "cv79", # y curly
    "cv74", # A curly
    "VXBI", # J simplest
    "cv83", # R curly
    "cv65", # 7 simpler
    "VXBI", # # straight with space
    "VXAL", # & weird
]

[buildPlans.iosevka-ak2.slopes]
upright = "normal"
italic = "italic"
# skip oblique

[buildPlans.iosevka-ak2.widths.normal]
shape = 500
menu  = 5
css   = "normal"

[buildPlans.iosevka-ak2-prose]
family = "Iosevka AK2 Prose"
quasiProportionalDiversity = 1
design = [
    "type", # "Sans"?
    "cv01", # a (default)
    "VXBM", # b rounded bottom
    "VXBP", # d rounded bottom
    "cv84", # f serifed
    "cv11", # g default
    "VXCB", # h default
    "cv06", # i asymmtetric serif
    "cv58", # j rounded
    "cv68", # k default
    "cv10", # l z shaped
    # "VXDA", # l asymmetric serif
    "cv26", # m with shorter middle leg
    "VXCF", # n default
    "VXCR", # p rounded top,
    "VXCS", # q rounded top
    "cv86", # r serif
    "VXDC", # t sharp bottom
    "cv90", # u rounded bottom
    "VXBF", # y with a tail
    "VXBD", # z default
    "cv73", # A default,
    "VXAQ", # B rounded
    "VXBG", # D default
    "cv92", # G rounded bottom
    "v-capital-j-serifed-both-sides", # J serif asymmetric?
    "VXCI", # M default
    "VXCA", # Q rounded bottom
    "cv82", # R default
    "cv80", # Y straight
    "cv13", # 0 slash
    "cv51", # 1 serif
    "cv46", # 3 sharp
    "VXAV", # 4 like calculator
    "VXAE", # 6 rounded bottom
    "VXAX", # 7 with cross over
    "cv96", # 9 rounded
    "cv17", # ~ middle
    "cv61", # * middle with 6 legs
    "cv30", # ^ middle
    "VXAO", # ( ROUNDED
    "cv37", # { middle
    "VXBJ", # # slanted with space
    "VXAI", # & rounded
    "cv32", # @ nice
    "cv54", # $ dollar small,
    "cv63", # % default?
    "cv67", # <= ligature"
]
# overload…
italic = [
    "VXBU", # a curly
    "cv53", # f curly
    "cv24", # g curly
    "VXCC", # h curly serif
    "cv04", # i curly asymmetric
    "VXDE", # j curly asymmetric
    "cv08", # l curly asymmetric serif
    "VXCT", # q curly rounded top
    "cv40", # t curly bottom
    "VXBT", # u curly
    "cv72", # v curly bottom
    "cv78", # x curly bottom
    "cv79", # y curly
    "cv74", # A curly
    "VXBI", # J simplest
    "cv83", # R curly
    "cv65", # 7 simpler
    "VXBI", # # straight with space
    "VXAL", # & weird
]

[buildPlans.iosevka-ak2-prose.slopes]
upright = "normal"
italic = "italic"
# skip oblique

[buildPlans.iosevka-ak2-prose.widths.normal]
shape = 576
menu  = 5
css   = "normal"