# VERSION 11

[buildPlans.iosevka-ak2]
family = "Iosevka AK2"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-ak2.variants.design]
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothed-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging"
capital-n = "asymmetric"
capital-p = "closed"
capital-q = "detached-bend-tailed"
capital-r = "standing"
capital-s = "serifless"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
b = "toothed"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey"
i = "serifed-asymmetric"
j = "serifless"
k = "curly-serifless"
l = "serifed-asymmetric"
n = "straight"
q = "straight-motion-serifed"
r = "serifless"
s = "serifless"
t = "flat-hook-short-neck"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "cursive"
z = "curly-serifed"
turn-v = "curly"
lower-lambda = "curly-turn"
lower-mu = "tailless"
zero = "dotted"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "open"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "curly-serifless"
eight = "two-circles"
nine = "closed-contour"
asterisk = "flip-penta-low"
pilcrow = "low"
caret = "medium"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright-open"
ampersand = "et-toothed"
at = "short"
dollar = "open-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "corner"
punctuation-dot = "round"

[buildPlans.iosevka-ak2.variants.italic]
a = "double-storey-serifed"
f = "flat-hook-tailed"
g = "double-storey-open"
i = "tailed-serifed"
j = "serifed"
k = "diagonal-tailed-cursive-serifless"
l = "tailed-serifed"
r = "corner-hooked"
y = "cursive-flat-hook"
z = "curly-serifed-with-horizontal-crossbar"
zero = "long-dotted"
ampersand = "flat-top"
dollar = "interrupted"

[buildPlans.iosevka-ak2.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ak2.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-ak2-prose]
family = "Iosevka AK2 Prose"
spacing = "quasi-proportional-extension-only"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-ak2-prose.variants.design]
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothed-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging"
capital-n = "asymmetric"
capital-p = "closed"
capital-q = "detached-bend-tailed"
capital-r = "standing"
capital-s = "serifless"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
b = "toothed"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey"
i = "serifed-asymmetric"
j = "serifless"
k = "curly-serifless"
l = "serifed-asymmetric"
n = "straight"
q = "straight-motion-serifed"
r = "serifless"
s = "serifless"
t = "flat-hook-short-neck"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "cursive"
z = "curly-serifed"
turn-v = "curly"
lower-lambda = "curly-turn"
lower-mu = "tailless"
zero = "dotted"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "open"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "curly-serifless"
eight = "two-circles"
nine = "closed-contour"
asterisk = "flip-penta-low"
pilcrow = "low"
caret = "medium"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright-open"
ampersand = "et-toothed"
at = "short"
dollar = "open-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "corner"
punctuation-dot = "round"

[buildPlans.iosevka-ak2-prose.variants.italic]
a = "double-storey-serifed"
f = "flat-hook-tailed"
g = "double-storey-open"
i = "tailed-serifed"
j = "serifed"
k = "diagonal-tailed-cursive-serifless"
l = "tailed-serifed"
r = "corner-hooked"
y = "cursive-flat-hook"
z = "curly-serifed-with-horizontal-crossbar"
zero = "long-dotted"
ampersand = "flat-top"
dollar = "interrupted"

[buildPlans.iosevka-ak2-prose.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ak2-prose.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
